import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/theme";
import { Footer, Header } from "@/components/layout";
import { Box, HStack } from "@chakra-ui/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <HStack display="flex" flexDirection="column" minHeight="100vh">
          <ThemeProvider>
            <Header />
            <Box flex="1">{children}</Box>
            <Footer />
          </ThemeProvider>
        </HStack>
      </body>
    </html>
  );
}
